language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "iojs"
before_script:
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
script:
  - gulp linter
  - gulp test
  - gulp dist
  - gulp jsdoc-style
  - gulp jsdoc