language: node_js
node_js:
  - "0.10"
  - "0.11"
before_script:
  - npm install -g gulp
  - npm install
script:
  - gulp linter
  - gulp test
  - rm dist/gama.min.js
  - gulp dist
  - git diff --exit-code